### ISSUE TITLE
Investigate inline styles not getting cleared out

### ISSUE THREAD

**Issue by swanson** [swanson/stringer#337]
Example: http://spin.atomicobject.com/2014/08/31/nature-matters-insights-on-biomimicry/

This post has inline styling on the image that cause it to overflow the container in Stringer. Loofah is supposed to handle this, so might need fixes upstream.

![image](https://cloud.githubusercontent.com/assets/56947/4110558/2182a53c-31f4-11e4-81a1-5e59d7998d15.png)

**Comment by Koronen** [comment]
@swanson is this still an issue?

**Comment by swanson** [comment]
?Yes - still an issue. Probably not helpful without a reproducible test case - I don't think we can access the RSS feed on that post any more since so much time has passed.


________________________________

**Comment by Koronen** [comment]
> Loofah is supposed to handle this, so might need fixes upstream.

In either case, it should be an issue on Loofah?

**Comment by swanson** [comment]
?I can get behind that - lets close the issue here.

________________________________
