### ISSUE TITLE
Options for PubSubHubbub in front of Stringer?

### ISSUE THREAD

**Issue by queuebit** [swanson/stringer#356]
@drdrang has been doing [some RSS](http://www.leancrew.com/all-this/2014/11/a-pubsubhubbub-test/) [experiments](http://www.leancrew.com/all-this/2014/11/the-rss-mess/) [this past week](http://www.leancrew.com/all-this/2014/11/more-rss-mess/). He is trying to see how updates to RSS items propagate to various services / clients via PubSubHubbub.

I tested both posts with updates on stringer and have older cached versions of the posts and was wondering what options are for a PubSubHubbub instance in between and whether they could push updates to a Stringer instance.

**Comment by swanson** [comment]
Closing this. Further discussion can take place below but there is nothing actionable here yet.
