### ISSUE TITLE
app.rb initialised before rake can create db

### ISSUE THREAD

**Issue by sjmog** [swanson/stringer#358]
It looks like app.rb is initialised for rake tasks and includes references to a db that doesn't yet exist. Maybe I'm being an idiot here, but any attempt to `rake db:migrate` in the dev environment throws:
```
FATAL:  database "stringer_dev" does not exist
app.rb:22:in `<class:Stringer>'
app.rb:18:in `<top (required)>'
```
(other error messages redacted for clarity)

**Comment by swanson** [comment]
Closing out this due to staleness - feel free to open if you are still having issues. (Sounds like there was a workaround in your case)
