### ISSUE TITLE
"foreman start" counterpart

### ISSUE THREAD

**Issue by contradictioned** [swanson/stringer#362]
How to stop this nice piece of software?
I did it the harsh way with htop and killing the process, but if there's another way, I think it should be documented.

Best regards.

**Comment by swanson** [comment]
`foreman` is not really meant to be backgrounded, so in theory you can just `CTRL+C` to stop it. If you are backgrounding it or starting it from a script or something, I think killing the process is probably the way to go

**Comment by contradictioned** [comment]
(nvm me forgetting having it run in a screen session :) )

**Comment by Koronen** [comment]
Pressing `Ctrl-C` with foreman running in the foreground and killing the foreman process using htop are equivalent (if using the default signal). Both methods send `SIGTERM` to the foreman process.
