### ISSUE TITLE
ruby 2.2

### ISSUE THREAD

**Issue by swanson** [swanson/stringer#364]
- [x] Check if upgrade works as expected
- [x] Add 2.2 to travis build matrix
- [x] Bump .ruby-version?
- [ ] Update deployment instructions (VPS, openshift, heroku)

**Comment by duenni** [comment]
Could this be an issue for Openshift users? You can only use Ruby 2.0 there...

**Comment by swanson** [comment]
Potentially, will add to checklist

**Comment by jeroenj** [comment]
It may not be 2.2 but I've been running it on 2.1.x for quite some time now. I'm planning to upgrade to 2.2 soon. I'll let you know (and/or provide PR's) if I find any issues. :)

**Comment by Koronen** [comment]
Ruby 2.2 was added to the Travis CI build matrix in #365.

**Comment by Koronen** [comment]
Sadly, the [Ruby "Overview" page on OpenShift](https://developers.openshift.com/en/ruby-overview.html) (at the time of this writing) still states that they only support Ruby 2.0 from the Ruby 2.x branch. :disappointed:

**Comment by bf4** [comment]
Any reason you lock the version to 2.0.0 in the Gemfile? That makes sense in your company, but in an OSS unless it is absolutely required, it could be just a recommendation or step in setup.

**Comment by swanson** [comment]
> Any reason you lock the version to 2.0.0 in the Gemfile? That makes sense in your company, but in an OSS unless it is absolutely required, it could be just a recommendation or step in setup.

@bf4 sorry for the late response here. Heroku advises adding a Ruby version to your Gemfile so that the deployed environment is explicitly defined. Since Heroku is the 'official' recommended deployment story, I've opted to add this as a convenience for those users. We want a smooth installation process, which means that we are a little more restrictive in the Ruby version that we recommend.

The trade-off is that folks deploying off the main path will have a little more work to do, but that is a decision that I decided I could live with :)

**Comment by bf4** [comment]
I have an incomplete PR which basically makes it configurable, but default to 2.0.0.  Would that be of interest?

**Comment by swanson** [comment]
> I have an incomplete PR which basically makes it configurable, but default to 2.0.0. Would that be of interest?

Happy to take a look at it :) As long as the Heroku considerations I mentioned above are satisfied, I'm open to it.

**Comment by dwaite** [comment]
Would this help with open shift users? https://github.com/openshift/sti-ruby

**Comment by moritzheiber** [comment]
[According to Heroku's website](https://devcenter.heroku.com/articles/ruby-support#supported-runtimes) Ruby 2.0.x will be EOL at the end of February (24th). Heroku is actively emailing customers, telling them to switch over to 2.2.4:

> On Feb 24, 2016, Ruby 2.0.0 security maintenance will reach its end-of-life. When this happens, Ruby 2.0.0 will no longer receive security updates. We recommend that you upgrade your app to a supported Ruby version, e.g. 2.2.4, to ensure that your application is running in a secure environment.
> After Feb 24, 2017, a year from the Ruby 2.0.0 sunset date, you will no longer be able to push your application using the official buildpack without upgrading to a supported Ruby version.

Seeing as though the newer Ruby has been around for some time, what's needed to be done to switch away from the obsolete version?

**Comment by bf4** [comment]
@swanson finally made that PR

**Comment by swanson** [comment]
RE: OpenShift, looks like a possible path forward is the Docker-based OpenShift 3 which could bundle newer ruby versions? https://blog.openshift.com/deploying-ruby-applications-on-openshift-3/

I'm not at all familiar with OpenShift as a platform, so might need some help investigating.

**Comment by swanson** [comment]
PR here: https://github.com/swanson/stringer/pull/416

Going all the way to 2.3.0

**Comment by swanson** [comment]
Ruby 2.3.0 is now the supported version on master

**Comment by duenni** [comment]
I don't know if that Docker stuff is available for **Openshift Online** (or just Openshift Origin) and also this is kind of a big hurdle. Until now you use a ruby-cartridge which is deployable in 10 secs and git-push to it. Now with Docker you have to know how all this stuff works, build docker images with other tools you haven't seen yet. Not to mention on how to update those stuff.
Is there a way back for Openshift users? What is the latest commit usable for Ruby 2.0?

For other Openshift users: you can vote for a ruby 2.3 cartridge [here](https://openshift.uservoice.com/forums/258655-ideas/suggestions/12476316-ruby-2-3-cartridge)

**Comment by swanson** [comment]
https://github.com/swanson/stringer/commit/6727f21a4fefb52923c47b09c5a8a0e075dba4ad is the latest commit before moving to 2.3

If 2.3 is not feasible yet, you could always modify the `.ruby-version` locally once you clone to use a supported version.
