### ISSUE TITLE
Auto-deploy button fails to deploy when custom URL has hyphen

### ISSUE THREAD

**Issue by mike-rogers** [swanson/stringer#367]
I clicked the deploy button, logged into Heroku, gave the application a name (which contained a hyphen), and watched the build fail with this message:

```
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
```

I then removed the hyphen and everything worked just fine.

**Comment by Koronen** [comment]
From what I can tell, this sounds more like an issue with Heroku than with Stringer. I tried, but failed to reproduce this -- my deploy succeeded.
![foo](https://cloud.githubusercontent.com/assets/543455/6511190/52dd8b70-c36b-11e4-925d-0f303c2f4339.png)

**Comment by mike-rogers** [comment]
Thanks for following up. I have no new information and only plan on deploying once. :wink: Feel free to close if you're comfortable.
