### ISSUE TITLE
VPS: stringer accepts connections, but doesn't handle them

### ISSUE THREAD

**Issue by zigdon** [swanson/stringer#370]
I have a couple instances of stringer running on my VPS. Things used to work fine, but with a recent upgrade, I'm seeing that when I start stringer, everything seems to work fine, but then after a while it stops responding to http requests.

Nothing obviously wrong looking at the foreman console:

```
$ foreman start
...
04:32:15 console.1 | Rack::Shell v1.0.0 started in production environment.
[1] pry(main)> 
```

Everything works fine, but after a while, incoming connections are just hanging:

```
carabiner$ telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
GET /
```

Just hangs.

**Comment by zigdon** [comment]
I did discover that if I do anything in the console when this happens, like typing '?', it seems to unblock and process more requests for a while. Then hangs again.

Makes me think there's some sort of buffer filling it. Is there a way I can just disable the console?

**Comment by swanson** [comment]
Sure - how about running `foreman start -c console=0`. That should not start the console process.

**Comment by swanson** [comment]
And if you want the nuclear option, just remove the `console` line from the `Procfile` :)

**Comment by zigdon** [comment]
If I try the -c option, it doesn't seem to keep the web server running?

**Comment by swanson** [comment]
Does `foreman start -c console=0,web=1` make it work?

**Comment by zigdon** [comment]
Yes!

So that's a valid workaround (assuming it doesn't hang in 30 minutes). Any
idea why it *would* hang with the console open? It didn't use to until
recently.

**Comment by andschwa** [comment]
Thanks for this workaround, I just upgraded the other day and was getting frustrated with the exact same bug!

**Comment by swanson** [comment]
Closing due to staleness, feel free to re-open if you are still having this issue.
