### ISSUE TITLE
Interested in a Dockerfile for stringer?

### ISSUE THREAD

**Issue by darron** [swanson/stringer#378]
Since Heroku's going to start charging for dynos soon, and because I wanted to figure out how, I got stringer working inside of a Docker container:

https://github.com/darron/stringer/commit/591cbb8d0677dbce8a970e74acdbe16a31d071e8

I'm using a Heroku Postgres DB - but the app is running inside a Docker container on a Digital Ocean instance.

Rake commands are much more complicated with this setup - I haven't even tried.

Most of the required ENV variables are passed along with the container starting - here's what I have setup:

```
/news/RACK_ENV:production
/news/SECRET_TOKEN:not-the-real-one
/news/STRINGER_DATABASE_HOST:hostname.compute-1.amazonaws.com
/news/STRINGER_DATABASE_PASSWORD:the-password
/news/STRINGER_DATABASE_PORT:5432
/news/STRINGER_DATABASE_USERNAME:the-username
/news/STRINGER_DATABASE:stringer
```

**Comment by swanson** [comment]
Nice - yeah, I'm always open to new deployment options. Someone else has done some work on this in the past: https://github.com/antonlindstrom/stringer-docker

Once you've got it fully ironed out, a pull request adding instructions to the `docs` folder would be great.

**Comment by swanson** [comment]
Hi @darron - going to close this issue. Feel free to re-open or pull request if you have any updates on this. Thanks for your interesting :)
