### ISSUE TITLE
Can't add some feeds

### ISSUE THREAD

**Issue by guiniol** [swanson/stringer#380]
I'm not sure if this is related to my setup, or if others have experienced it.
Sometimes, when I try to add a feed, I get a `feed_not_found_error`, and after a few tries it goes through. I'm using stringer on a free instance of RedHat Cloud.
For example, I haven't been able to add this feed: https://copperhead.co/feed.xml

Tell me if there is any info I can provide. I'm not sure how to debug that.

**Comment by Koronen** [comment]
To me this sounds like temporary issues with connectivity, so I'm not sure what we can do on our part. Does this affect fetching of any other feeds?

**Comment by guiniol** [comment]
All my other feeds were refreshing properly. I tried the feed mentionned in my first comment for about a week without luck, so I posted the issue in case it was a problem bigger than connectivity.

**Comment by Koronen** [comment]
Hey @guiniol, thank you for reporting this issue. I'm going to close this now due to inactivity. Feel free to re-open if you have any updates on this.

**Comment by guiniol** [comment]
Alright. I haven't updated in a while, so I'll try and check how it goes.

**Comment by matthiasballreich** [comment]
ticket should be re-openend, because this error still exists. Not only on the RSS in the first post, here: http://www.drwindows.de/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=10, too :/ Stringer could not fetch the feed.

**Comment by guiniol** [comment]
Definitely. I checked and forgot to come back and say that it still doesn't work.

**Comment by Koronen** [comment]
None of these feeds pass the W3C Feed Validation Service at the time of this writing.

https://copperhead.co/feed.xml
> Server returned [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error [help]

http://www.drwindows.de/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=10
> * description contains bad characters
> * description should not contain attachment140530" attribute
> etc.

**Comment by matthiasballreich** [comment]
yeah i tried it myself with the W3C Feed Validator and the rist one is not valid, but the second one ist valid. W3C says it is a valid Feed. The Messages are only Recommendations like not using attachment attribute, etc.

**Comment by Koronen** [comment]
The error with the `www.drwindows.de` feed appears to be related to Feedjira and the options we pass to it.
```
$ racksh
Rack::Shell v1.0.0 started in development environment.
[1] stringer-development(main)> url = "http://www.drwindows.de/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=10"
=> "http://www.drwindows.de/external.php?do=rss&type=newcontent&sectionid=1&days=120&count=10"
[2] stringer-development(main)> options = {user_agent: "Stringer (https://github.com/swanson/stringer)", if_modified_since: Time.now, timeout: 30, max_redirects: 2, compress: true}
=> {:user_agent=>"Stringer (https://github.com/swanson/stringer)",
 :if_modified_since=>2016-01-30 13:15:07 +0100,
 :timeout=>30,
 :max_redirects=>2,
 :compress=>true}
[3] stringer-development(main)> Feedjira::Feed.fetch_and_parse(url, options)
/home/koronen/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/feedjira-1.3.0/lib/feedjira/feed.rb:237: warning: uncaught exception from callback
=> 200
[4] stringer-development(main)> Feedjira::Feed.fetch_and_parse(url)
=> #<Feedjira::Parser::RSS:0x007f73959667b0 ...>
```

**Comment by matthiasballreich** [comment]
so i should report it to the developer of Feedjira?

**Comment by guiniol** [comment]
I have found another feed which I cannot add to stringer: https://blog.patternsinthevoid.net/feeds/all.atom.xml
This feed does not pass the w3c validation. If I understood correctly from the previous comments, this should be reported directly to feedjira to see if they want to support such feeds, right?

**Comment by gabrielpoca** [comment]
Hey @guiniol can I close this, or is still a problem?

**Comment by guiniol** [comment]
Seems to work now, so sure, go ahead!
