### ISSUE TITLE
prevent SSL-stripping MITM using HTTP Strict Transport Security

### ISSUE THREAD

**Issue by InPermutation** [swanson/stringer#382]
When terminating requests with SSL, you should enable [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).

Heroku serves a wildcard *.herokuapp.com certificate, so for most people, HSTS should be enabled.

If you're developing on localhost, hosting Stringer on a VPS but you don't want to pay for a certificate, or using a CNAME without installing the Heroku SSL addon, you won't have SSL. In those cases, HSTS should not be enabled.

**Comment by swanson** [comment]
Hey Jacob - what is the action to take in this repo? Is this a configuration option we need to be including? Updates to installation docs? It seems this is more of a deployment concern based on what you've written here.

**Comment by InPermutation** [comment]
1. Add a configuration option named something like `Force HTTPS`
2. If set, add a header, `Strict-Transport-Security: max-age=31536000`
3. Set this configuration option to `true` for Heroku Button installations

The max-age value of 31536000 is approximately one year, adjust to taste.

**Comment by jhass** [comment]
You can just conditionally insert https://github.com/josh/rack-ssl

**Comment by InPermutation** [comment]
Yeah, what @jhass said - that will additionally redirect to https if http is accidentally typed the first time, and set all cookies as `; secure`

**Comment by Koronen** [comment]
> Add a configuration option named something like `Force HTTPS`

`ENFORCE_SSL` https://github.com/swanson/stringer/blob/527491dbe1585c8fddbc6908d0fc480f83fe5166/app.rb#L20

> If set, add a header, `Strict-Transport-Security: max-age=31536000`

`rack-ssl` does this for us, if enabled.
https://github.com/josh/rack-ssl/blob/v1.4.1/lib/rack/ssl.rb#L28

> Set this configuration option to `true` for Heroku Button installations

#383

> You can just conditionally insert https://github.com/josh/rack-ssl

We already do this. https://github.com/swanson/stringer/blob/527491dbe1585c8fddbc6908d0fc480f83fe5166/app.rb#L20

**Comment by jhass** [comment]
I guess that makes this a documentation issue ;)

**Comment by InPermutation** [comment]
#383 resolves everything in this issue :+1:
