### ISSUE TITLE
Download aggregated RSS feed from stringer itself

### ISSUE THREAD

**Issue by maxmeyer** [swanson/stringer#398]
Hi, 

I search a bit for mobile clients supporting the fever API. Unfortunately I only found [press](http://twentyfivesquares.com/press/) which is quite outdated and did not get updates for more than one year. So this app seems to be a dead end. Any other suggestion for Android?

Now coming to my next question: Does stringer itself provide an aggregated rss feed? Something I can access via `http://stringer:<password>@rss.example.com/news/rss`? If this is or would be possible I could just use a simple rss feed reader.

I know that this approach has "some" limitations like non-synced status, but at least I could access the aggregated feed. Alternatively something like this might be doable: pass arguments like `http://stringer:<password>@rss.example.com/news/rss?status=read` to stringer, to set the status of alle messages in RSS feed to read.

Thanks a lot.

Cheers,
Dennis

**Comment by jeroenj** [comment]
It does not provide an aggregated RSS feed and I don't think it ever will. (but obviously it's not my decision). I think it would be out of scope of what the app should do.

What might be an option is that if there is an other "open" API format that could be supported. But of course that would imply that it would need to be implemented for stringer.

**Comment by pascalw** [comment]
Probably your best bet would be to create a custom feed based on the Fever API that Stringer provides. 

You could create a script that parses the API response and converts that into an RSS feed and throw that up on Heroku. Combine that with a cronjob on your Stringer instance that deletes old articles and you're done.

I've build [a tool](https://github.com/pascalw/scriptor) some time ago that can turn webpages and API responses into RSS feeds which you could use for this purpose. Docs are scarce though so use at your own risk :-)

**Comment by Koronen** [comment]
> I think it would be out of scope of what the app should do.

I agree with this. I don't see Stringer being the component that aggregates feeds in the sense described in this issue.

@maxmeyer, thank you for asking and I hope you find another solution that suits your needs.
