### ISSUE TITLE
Remove request to Google Fonts

### ISSUE THREAD

**Issue by mario-areias** [swanson/stringer#399]
First, I am not really sure if that's a issue for everybody, but it is for me. In `layout.erb` file there is a request to get Lato Fonts at Google. Even though, I understand why is there, it is an issue for me. I would like to have less external dependencies as possible, to make sure I don't send information for organisations or people that I don't want to :) 

Again, I understand that might not be an issue for everybody. But in case it is, I've [fixed that](https://github.com/mario-areias/stringer/commit/ba4adfbcbea5eddeb0f7caebfd01431b93ab6f28) in my fork and would be happy to make a PR with it. Please feel free to close this, if you think that's not an issue.

**Comment by swanson** [comment]
I can certainly understand that stance. You'll also want to do the same for 'Reenie Beanie' font used in the tutorial: https://github.com/swanson/stringer/blob/b221b6479c14d07881c3b4f9bfc65c31d7a3cbc6/app/views/tutorial.erb#L1-L3

I'd be open to a PR to self-host the fonts (we already do it for FontAwesome), assuming that is in compliance with the font licenses

**Comment by mario-areias** [comment]
Yes, I found that font as well in tutorial, although I didn't find any where in my app that was using this one, so I didn't fix it. I can make a PR with both changes, if you would like to.

**Comment by mario-areias** [comment]
It seems both fonts use the same license and the license allows to have them hosted. I went ahead and created a PR. I also tested locally and looks fine, please let me know if that works for you.

**Comment by swanson** [comment]
Merged.
