### ISSUE TITLE
Machine learning doesn't work

### ISSUE THREAD

**Issue by tschellenbach** [swanson/stringer#409]
So I checked it out and the machine learning doesn't work

**Comment by swanson** [comment]
> Stringer has no external dependencies, no social recommendations/sharing, and no fancy machine learning algorithms.

WONT-FIX ;)

**Comment by tschellenbach** [comment]
Yeay it's a joke, great post
http://mdswanson.com/blog/2016/01/25/sell-or-kill.html!
