### ISSUE TITLE
always require login when using subdomain

### ISSUE THREAD

**Issue by ericyue** [swanson/stringer#413]
I start my reader servise on port 5833
in nginx conf, I mapping xxx.xxx.com to 127.0.0.1:5833
I can do everything using ip_address:5833
but when i using xxx.xxx.com to add feed, always require login .
how to solve this ?
I'm running in my vps

**Comment by ericyue** [comment]
more :    when i using subdomain to delete one feed, it's warning: something broke!

**Comment by ericyue** [comment]
more info， I setup stringes using ip:port , then configure nginx proxy set 
server {
        listen 80;
        server_name xxx.xxx.com;
        location / {
                proxy_pass http://127.0.0.1:5833;
        }
}

**Comment by malantonio** [comment]
I ran into this problem as well, @ericyue. I found that adding `proxy_set_header Host $host;` fixed this.

```
server {
        listen 80;
        server_name xxx.xxx.com;
        location / {
                proxy_pass http://127.0.0.1:5833/;
                proxy_set_header Host $host;
        }
}
```

Hope that helps!

**Comment by ericyue** [comment]
thanks malantonio! It works!
