### ISSUE TITLE
Update OpenShift docs for Ruby 2.3.0

### ISSUE THREAD

**Issue by swanson** [swanson/stringer#420]
https://github.com/swanson/stringer/blob/master/docs/OpenShift.md

Potential resources: 
https://blog.openshift.com/deploying-ruby-applications-on-openshift-3/
https://github.com/openshift/sti-ruby

**Comment by duenni** [comment]
So, Openshift Online 2 is EOL by September 30th and will no longer be available.
There are docs on how to migrate to Openshift Online 3 [here](https://blog.openshift.com/migrating-your-applications-from-openshift-2-to-3/). 
Has anybody successful migrated an existing stringer deployment from Openshift 2 to Openshift 3?

Are there any experiences on how to setup stringer on Openshift 3?

**Comment by guiniol** [comment]
I took a look at their doc, and switched to heroku...

**Comment by gabrielpoca** [comment]
Unfortunately I don't know anything about OpenShift, is there anyone willing to help? I think that we should either update the docs or remove them altogether, the docs for a EOL version don't have any value.
