### ISSUE TITLE
Investigate upgrading to Feedjira 2.0

### ISSUE THREAD

**Issue by swanson** [swanson/stringer#422]
https://github.com/feedjira/feedjira/tree/v2.0.0

Relevant code: 
https://github.com/swanson/stringer/blob/master/app/tasks/fetch_feed.rb
https://github.com/swanson/stringer/blob/master/app/utils/feed_discovery.rb

**Comment by gabrielpoca** [comment]
This was solved in https://github.com/swanson/stringer/pull/448
