### ISSUE TITLE
Where in the codebase should I look to lift time-based restrictions on RSS items?

### ISSUE THREAD

**Issue by Hunter-Github** [swanson/stringer#425]
Some feeds I'm subscribed to don't have this 'Breaking News!' mentality and tend to date articles a bit more haphazardly. With the current stringer setup, I don't receive them at all. Where in the codebase should I look to be able to remove or modify the constraint?

**Comment by Koronen** [comment]
You could have a look at [`FindNewStories#new_stories`](https://github.com/swanson/stringer/blob/0dd251cbfcac5d4e6415cf6b1788979218771edc/app/commands/feeds/find_new_stories.rb#L13-L23).

**Comment by Hunter-Github** [comment]
Thank you, fiddling with `STORY_AGE_THRESHOLD_DAYS` now.
