### ISSUE TITLE
Ability to clean out the DB

### ISSUE THREAD

**Issue by lorentrogers** [swanson/stringer#435]
The Heroku free tier has a limited number of rows you can have in a DB. There should be some way to either clean out old content manually or have Stringer automatically trash it. An automated system would be ideal, as long as there's a way to choose how much to keep.

Thoughts?

**Comment by Koronen** [comment]
> You can clean up old stories by running: `rake cleanup_old_stories` /--/ You can either run this manually or add it as a scheduled task.

https://github.com/swanson/stringer/blob/master/README.md#clean-up-old-read-stories-on-heroku

See also https://devcenter.heroku.com/articles/scheduler.

**Comment by lorentrogers** [comment]
Perfect - that should do it. Any thoughts about pulling this functionality into the app interface?
