### ISSUE TITLE
Cannot run rake db:migrate (NameError: uninitialized constant...)

### ISSUE THREAD

**Issue by jeffmikels** [swanson/stringer#436]
I'm fairly new to rails development, and attempting to deploy to Heroku using the purple button didn't work for some reason, so I'm following the manual method and I get this error while running

rake db:migrate

    NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails
    /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:55:in `db_dir'
    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/rake.rb:112:in `db_dir'
    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/rake.rb:67:in `dump_schema'
    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/tasks.rake:58:in `block (3 levels) in <top (required)>'
    /app/vendor/bundle/ruby/2.3.0/gems/sinatra-activerecord-1.7.0/lib/sinatra/activerecord/tasks.rake:34:in `block (2 levels) in <top (required)>'
    Tasks: TOP => db:schema:dump

I read elsewhere that the current ActiveRecord is not compatible with sinatra 1.7. Does anyone have a solution to this?

**Comment by Koronen** [comment]
I get a feeling this might be related to me upgrading a whole bunch of gems in #428, specifically 81a60ac44197a021aa8a7b9876acb3b6642436d8.

**Comment by guiniol** [comment]
I think I had the same problem in #436, so I tried a8ca8669 (parent of 81a60ac) and indeed the error disappears. The app is not functionning properly though, but I can't say if it's my fault or a bug (because it's my first time using sandstorm.io and I have no idea if I'm doing things right ^^)
