### ISSUE TITLE
Install instructions for sandstorm.io

### ISSUE THREAD

**Issue by guiniol** [swanson/stringer#437]
This is low priority, and I'll spend more time investigating further, but I figured others might be interested.

Since there are problems with openshift's ruby, I went looking for other free providers and found sandstorm.io. I'm trying to create an app in their format, which amounts to taking parts of the VPS install instruction and pasting it in the right scripts ([scripts attached](https://github.com/swanson/stringer/files/257378/sandstorm.zip)). Once the app works, it can be uploaded to their site and anyone could install it in one click, or a new install instruction page could be created with the 3 scripts and anyone could install it. However, I haven't been able to get it to work yet. I don't know why, but the `bundle exec rake db:migrate RACK_ENV=production` fails with `NameError: uninitialized constant ActiveRecord::Tasks::DatabaseTasks::Rails`.

**Comment by swanson** [comment]
Same issue as #436 perhaps?

**Comment by guiniol** [comment]
The errors look very similar, yes. I'm pretty new to both sinatra and sandstorm, so I'll post my progress here as I try to understand what is going on.

**Comment by guiniol** [comment]
As I mentioned in #436, reverting to a pre 81a60ac commit fixes this issue.
But it still doesn't work ^^

**Comment by guiniol** [comment]
Would it be ok to reopen this issue, since the sandstorm.io app isn't quite working yet. I'll spend more time to get it to work, but I think it's better to have this open to show that I'm working on it. Plus others might want to contribute.

**Comment by guiniol** [comment]
@swanson thanks for reopening the issue.
Is there anyway to get logs from stringer? I see a `log/` directory, but it's empty.

**Comment by gabrielpoca** [comment]
Hey @guiniol , are you still interested in this issue or can I close it?

**Comment by guiniol** [comment]
I gave up, sorry.
