### ISSUE TITLE
Some feeds not showing up

### ISSUE THREAD

**Issue by mockdeep** [swanson/stringer#439]
I have a feed that I follow that I haven't seen any updates for a while: http://backcomic.com/rss.xml

If you look at the feed, it's been updated fairly often, and if I look at the feeds view in Stringer, it shows up with the most recent date:
![back](https://cloud.githubusercontent.com/assets/80543/15456275/eecc3e16-201f-11e6-93b5-e2ea4f2a6931.png)

But I haven't actually seen any of the last 15 or so entries. Any idea what's going on?

**Comment by dperson** [comment]
Hmm, it actually does validate on https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fbackcomic.com%2Frss.xml

**Comment by gabrielpoca** [comment]
@mockdeep is this still a problem?

**Comment by mockdeep** [comment]
@gabrielpoca I haven't seen an update from that feed in quite a while, but it looks like they might have changed the feed url to http://www.backcomic.com/rss.xml, so I'll have to see what happens with that.

**Comment by gabrielpoca** [comment]
@mockdeep is it ok if I closed this for now? I'm trying to clean it up. I'll definitely look into it if it's still an issue.

**Comment by mockdeep** [comment]
Yeah, I think this is still an issue. I updated the feed and it still hasn't updated after a day.

**Comment by gabrielpoca** [comment]
@mockdeep I found the problem. The items in that feed have the following structure.

```xml
<item>
  <link>http://backcomic.com/164</link>
  <description>
    <img src="http://backcomic.com/s/Back10_026_jpfvcz.png"><img 
    src="http://backcomic.com/s/Back10_027_2g81tm.png">
  </description>
  <pubDate>Wed, 25 Oct 2017 00:00:00 -0600</pubDate>
  <guid isPermaLink="true">http://backcomic.com/164</guid>
</item>
```

Notice that there isn't a `title` property. That is ok, [everything is optional, it only needs to have either a title or a description](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt). The problem is that this feed uses the description field as the content, and I don't think that's a problem stringer should be solving. What do you think?

**Comment by mockdeep** [comment]
@gabrielpoca Hmm, so It looks like other sites [like xkcd]( https://xkcd.com/rss.xml) also put the content in the description. Is the difference that they at least have a `title` attribute as well? If so, I guess the above seems like a case that should be supported by stringer, maybe with just a "(no title)" message of some sort or swap in the feed title.

```xml
<item>
  <title>Defensive Profile</title>
  <link>https://xkcd.com/1911/</link>
  <description>
    <img src="https://imgs.xkcd.com/comics/defensive_profile.png" title="NO DRAMA ZONE -> If I've made you sad, you'd better not tell me, because I am TERRIFIED of that situation and have NO IDEA how to handle it." alt="NO DRAMA ZONE -> If I've made you sad, you'd better not tell me, because I am TERRIFIED of that situation and have NO IDEA how to handle it." />
  </description>
  <pubDate>Fri, 03 Nov 2017 04:00:00 -0000</pubDate>
  <guid>https://xkcd.com/1911/</guid>
</item>
```

**Comment by gabrielpoca** [comment]
@mockdeep that makes sense, but if I understood correctly the specification, if there isn't a title, then I should use the description, which in the case of your feed would give you a title like "<img ... />". Or am I missing something?

**Comment by mockdeep** [comment]
@gabrielpoca I guess I'd be fine with that. I'd rather anything show up than nothing, so an escaped image tag seems fine to me. It also kind of makes sense to me in terms of what the spec says.

**Comment by mockdeep** [comment]
Side note, I've got a [couple](http://feeds.megaphone.fm/sciencevs) of [other](http://feeds.feedburner.com/pod-save-america) feeds that are showing as red. Should I open a new issue for those?

**Comment by gabrielpoca** [comment]
There's no need, I'll try to look into it this week 👍

**Comment by gabrielpoca** [comment]
Hi @mockdeep I just opened a [PR](https://github.com/swanson/stringer/pull/467) to solve the issue with the first feed, but I cannot find anything wrong with the other ones, they were working just fine. Can you confirm?

**Comment by mockdeep** [comment]
Awesome, thanks! I took another look at the other feeds. The [ScienceVS](http://feeds.megaphone.fm/sciencevs) one shows as green and as having updated November 16, but I have not seen any actual items show up in my list. [Pod Save America](http://feeds.feedburner.com/pod-save-america) shows up red and as having updated on November 20, but again, nothing has showed up in my feed in a few months. The error says it has never worked, which seems weird.

**Comment by mockdeep** [comment]
Actually, I just pulled down and deployed the latest commits from `Stringer` and a bunch of stuff showed up in my feeds, including some of the Pod Save America stuff. However, the links aren't working on the Pod Save America stuff. They just link to `/news`.

**Comment by gabrielpoca** [comment]
@mockdeep it seems that items on that feed don't have any URL

```
<item>
--
  | <title>"Don't Hiss. Vote." (LIVE from Richmond)</title>
  | <description>
  | <![CDATA[<p>The Virginia race, the DNC and Brazile-gate, and the possibility of a shutdown for Dreamers. Lt. Governor Ralph Northam, Justin Fairfax, Attorney General Mark Herring, and Symone Sanders join Jon, Jon, Tommy, and Dan on stage live from Richmond, Virginia.</p>]]>
  | </description>
  | <itunes:title>"Don't Hiss. Vote." (LIVE from Richmond)</itunes:title>
  | <itunes:episodeType>full</itunes:episodeType>
  | <itunes:summary>The Virginia race, the DNC and Brazile-gate, and the possibility of a shutdown for Dreamers. Lt. Governor Ralph Northam, Justin Fairfax, Attorney General Mark Herring, and Symone Sanders join Jon, Jon, Tommy, and Dan on stage live from Richmond, Virginia.</itunes:summary>
  | <content:encoded>
  | <![CDATA[<p>The Virginia race, the DNC and Brazile-gate, and the possibility of a shutdown for Dreamers. Lt. Governor Ralph Northam, Justin Fairfax, Attorney General Mark Herring, and Symone Sanders join Jon, Jon, Tommy, and Dan on stage live from Richmond, Virginia.</p>]]>
  | </content:encoded>
  | <guid isPermaLink="false">gid://art19-episode-locator/V0/59FVIQxWSugLa50r8YB7-H1KaFjsS0f0Ugd8a2JWDjA</guid>
  | <pubDate>Mon, 06 Nov 2017 17:52:42 -0000</pubDate>
  | <itunes:explicit>yes</itunes:explicit>
  | <itunes:image href="https://dfkfj8j276wwv.cloudfront.net/images/0d/28/33/81/0d283381-724c-4caa-abad-b470e950d72d/b81bc65ae9ed5e2c095d68d40fecf3735467132e22415ad4861dd89a2f6527a47f45269a9091f8e98b499f5abc6c0c5423daa6690324ee9a0b9572868319deb7.jpeg" />
  | <itunes:keywords>tommy vietor,donald trump,Jon Lovett,Pod Save America,politics,POTUS,Dan Pfeiffer,jon favreau</itunes:keywords>
  | <itunes:duration>01:34:37</itunes:duration>
  | <enclosure url="https://rss.art19.com/episodes/8ec7727f-0589-4c80-813e-49349155b5a3.mp3" type="audio/mpeg" length="90845936" />
  | </item>
```

It probably should show a media player with the MP3, but stringer isn't really fit to listen to podcasts. What do you think?

**Comment by mockdeep** [comment]
@gabrielpoca hmm, can you take the `enclosure` url and link to that? With these all I really want to do is download the mp3 and listen to it.

Thanks for all the help, btw.

**Comment by mockdeep** [comment]
Another example: https://rss.art19.com/the-daily

**Comment by gabrielpoca** [comment]
Hi @mockdeep solved in [this commit](https://github.com/swanson/stringer/commit/b4ae4c1d43c9f0bd597e76dcb3324ac6f89e8359). Please let me know if I managed to fixed this time :p

**Comment by mockdeep** [comment]
Excellent! I guess it doesn't work for feeds that have already been added, so I'll have to report back after some new ones trickle in. Feel free to close this issue if you like. Thanks so much!

**Comment by mockdeep** [comment]
Alright, it works! Thank you!

**Comment by gabrielpoca** [comment]
Cool! :p
