### ISSUE TITLE
Mark all as read

### ISSUE THREAD

**Issue by duenni** [swanson/stringer#443]
Hi there,

I am experimenting with stringer on a Raspi. Unfortunately I let it stay with dozens of feeds, did not read stories for weeks and now it seems the memory on the pi exhausted or something. I always get a `502 Bad Gateway` when trying to access the main page. I can access `mystringer.url/archive`, `mystringer.url/starred` and so on but not the main page (connection gets closed prematurely). Is there a way to mark all items as read from a browser? I think I have seen something like `mystringer.url/mark_all_as_read` but I can't remember the exact string.
Thanks in advance!

**Comment by swanson** [comment]
You can do an  HTTP POST to "/stories/mark_all_as_read". It's not particularly easy to do that in a browser, but you might be able to use an extension like PostMan to achieve the POST.

Another option would be to mark the stories as read manually in the database.

**Comment by duenni** [comment]
Ok, thanks.

> Another option would be to mark the stories as read manually in the database.

How can I do this?

**Comment by swanson** [comment]
SSH into the box, change to the app directory.

Run `racksh` -- that should bring up a console. Then do `Story.all.update_all(is_read: true)`.

Haven't tested that and doing it from memory, but maybe that will get you close :)

**Comment by duenni** [comment]
Yes, it's working! Brings stringer back to life on my pi. Thanks again! 👍
