### ISSUE TITLE
Any planned support for https://jsonfeed.org/ ?

### ISSUE THREAD

**Issue by queuebit** [swanson/stringer#452]
Here is an example feed backend for Jekyll (not me): https://ndarville.com/blog/2017/05/19/json-feed-for-jekyll/

The background for why `jsonfeed.org` on the latest episode of [The Talk Show](https://daringfireball.net/thetalkshow/2017/05/31/ep-192).

**Comment by gabrielpoca** [comment]
HI @queuebit thank you for opening an issue. I am not familiar with jsonfeed, are there blogs that offer jsonfeed an not rss?

**Comment by queuebit** [comment]
`jsonfeed` is supported as part of the new <http://micro.blog> rollout, but I don't think there is really any content providers that will be `jsonfeed` _only_ for a long time.

The whole idea behind it though, is that it is a much simpler format to support both for content creators to support (few parsing errors) and since there are fewer xml parsing errors, fewer feed bugs that get related back to the client app.

This is more of a "cool feature to implement at some point if I or others think it is cool," but definitely doesn't need to be a *required* feature of stringer. So depending on how issues are being handled right now, feel free to leave open or prospectively close it.

**Comment by swanson** [comment]
Probably an upstream feature for Feedjira I'd think.

**Comment by gabrielpoca** [comment]
That would be the best option, but Feedjira describes itself as `a Ruby gem for fetching and parsing RSS feeds.`.

**Comment by queuebit** [comment]
Yep, looks like Feedjira is going to attempt support: https://github.com/feedjira/feedjira/issues/387

Thanks.
