### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by kehao95** [swanson/stringer#453]
I don't know if it's possible to run stringer in docker. If so, I suggest add a Dockerfile.

**Comment by AnthonyMastrean** [comment]
Relates to #378

**Comment by gabrielpoca** [comment]
I'm closing this issue because it was solved in [this](https://github.com/swanson/stringer/commit/0fa6cd29ef3d92fd1273d6805c2fa2b0602cf17d) commit.
