### ISSUE TITLE
Is the cleanup task not working or is Heroku mixed up?

### ISSUE THREAD

**Issue by AnthonyMastrean** [swanson/stringer#455]
I have an old Stringer running on Heroku, deployed with the "Deploy to Heroku" button, with no unread items and no starred items. Except, now, I'm getting emails about resource usage.

![image](https://user-images.githubusercontent.com/217842/29843931-9700eb4e-8cdb-11e7-93e9-cc37b0c945dd.png)

The cleanup task is scheduled and, apparently, running successfully.

![image](https://user-images.githubusercontent.com/217842/29843764-06d72114-8cdb-11e7-9481-6cac2529f6a3.png)

https://github.com/swanson/stringer/blob/master/Rakefile#L65

And the database stats page does not agree about the row size

![image](https://user-images.githubusercontent.com/217842/29844156-5adcb804-8cdc-11e7-998b-bd8b5a6f0243.png)

Or is this something I should report to Heroku (unlikely to get good support, as I'm not paying for this app)?

**Comment by swanson** [comment]
Yeah, I'd take it up with Heroku, might have just been a bug in sending the email. I'm not aware of any changes to the 10k row limit that would cause this, but maybe they are including 10k total rows overall? Regardless of current size?
