### ISSUE TITLE
Setup automated build to Docker hub

### ISSUE THREAD

**Issue by pascalw** [swanson/stringer#458]
Now that we have a Dockerfile it would be nice to setup an automated build to Docker hub.

That way people don't have to build the image themselves but can simply run `docker run stringer/stringer`.

Setting this up should be pretty simple, steps are outlined at https://docs.docker.com/docker-hub/builds/#create-an-automated-build. However I do think it needs to be done by the repository owner, or perhaps a collaborator. @swanson or @gabrielpoca could one of you have a look at this?

**Comment by gabrielpoca** [comment]
@pascalw 👍 I will take care of in the following days

**Comment by gabrielpoca** [comment]
@pascalw it seems that I cannot do it either, only the owner. swanson if you setup the account and invite me, I could take care of the configuration.

**Comment by swanson** [comment]
Sorry, I'm not super familiar with the docker ecosystem -- I should register for Docker Hub and invite @gabrielpoca to join the Docker Hub account?

**Comment by swanson** [comment]
I think I've setup everything: https://hub.docker.com/r/mdswanson/stringer/ (both `swanson` and `stringer` namespaces were taken already)

**Comment by pascalw** [comment]
@swanson nice 👍 ! I'll update docs to reflect this.
