### ISSUE TITLE
Categories/Grouping for feeds

### ISSUE THREAD

**Issue by Daegalus** [swanson/stringer#46]
I think it would be nice to have a way to categorize feeds into groups.

I currently use Feedly, and would like to move away from it, but I rely a bit on groups to focus my reading since I have anywhere from 700-800 newsfeed entries a day, and its a bit rough having them all just in 1 list.

**Comment by swanson** [comment]
Closing due to lack of interest. Feel free to comment if anyone wants to continue discussion, but no action has been taken in over a year :)

**Comment by jeffmikels** [comment]
I'm interested in this, but I don't know Ruby programming. I'll see if I can make some UI happen, but it would be nice to know if anyone else is interested in working on it with me.
