### ISSUE TITLE
Is there a way I can set it to delete read stories straight away? 

### ISSUE THREAD

**Issue by thestudentjoseph** [swanson/stringer#473]
Hi, I subscribe to a lot of feeds for work but I only need to scan them and then mark them as read. I don't need them after that. 

Is there a way to set it to delete stories after they are already read. Like a rake job or something like that?

**Comment by swanson** [comment]
You can run `rake cleanup_old_stories` to delete old stories. It defaults to only deleting stories that are over 30 days old, but you can pass it a parameter if you'd prefer `rake cleanup_old_stories[7]` for over 7 days old.

You can run this rake task on a cron job.

Alternatively, you could fork the project and modify the "mark as read" endpoint to also delete the story.

**Comment by thestudentjoseph** [comment]
Thanks so much. Running the cron job fixes everything.
