### ISSUE TITLE
Add feed URL / bookmarklet

### ISSUE THREAD

**Issue by nicholasgodbout** [swanson/stringer#482]
Requesting a feature:

Add a feed by going to stringer/feeds/new?url=%s

**Comment by m0nhawk** [comment]
I'm using the following with "RSS Subscription Extension":

```
.../feeds/new?feed_url=%s
```

**Comment by nicholasgodbout** [comment]
Ah-ha! Thanks!

**Comment by mockdeep** [comment]
Looks like this feature is already implemented.
