### ISSUE TITLE
One single story getting fetched during `fetch_feeds`

### ISSUE THREAD

**Issue by vcavallo** [swanson/stringer#489]
Hello.
I've followed the instructions and deployed manually to Heroku. I added three feeds (https://codewithoutrules.com/atom.xml, http://what-if.xkcd.com/feed.atom, http://blog.vinneycavallo.com/feed.xml) and ran `fetch_feeds`. The most recent post from codewithoutrules.com appears, but _nothing else_. I've deleted these three feeds and tried again with the same result. No error messages on the rake task.

The only manner in which I steered off the path of the directions was deploying to `heroku-16` stack, because the ruby version was unsupported by `heroku-18` (the one-click installer didn't work as a result). Could this be the reason?

**Comment by vcavallo** [comment]
... I just realized that the single post I'm referring to was published less than 24 hours ago. The other feeds don't have recent items.
So if stringer is not attempting to fetch _older_ items, then there is nothing broken here and this can be closed :)

**Comment by swanson** [comment]
Hi, when a feed is added, we only pull stories from the past day. You can see the relevant code here (if you're interested in modifying it for your own instance: https://github.com/swanson/stringer/blob/master/app/commands/feeds/add_new_feed.rb#L13)

Many blogs would have hundreds (if not thousands) of old stories and pulling them all in as unread stories was not desirable.
