### ISSUE TITLE
Instructions on FreeBSD

### ISSUE THREAD

**Issue by contradictioned** [swanson/stringer#495]
Are you interested in adding instructions for installing stringer on FreeBSD in `docs/VPS.md`? If so, I am just installing it there and could write something down.

**Comment by mockdeep** [comment]
Hey @contradictioned, I know it's been forever since you opened this issue, but BSD instructions would be welcome. I'm guessing you're not so fresh on it anymore, though, so no biggie.

**Comment by contradictioned** [comment]
Oh didn't know the project was un-archived :)
But yes, unfortunately, my BSD-endeavor has ended... if someone has concrete problems (and find this issue) they can ping me.
