### ISSUE TITLE
High CPU usage from racksh

### ISSUE THREAD

**Issue by charlesoblack** [swanson/stringer#511]
I'm running two instances of stringer on a VPS, installed manually (not via Docker).

For some reason, they're giving me very high CPU usage from `racksh`. It seems `rake work_jobs` is the culprit somehow. The processes get killed after a few (1-5) seconds, but keep getting respawned.

This is happening when running stringer via systemd, but not via foreman. Any clue as to why this might be? I can't find where logs might be for this but I can look into them if you tell me where they are, then report back.

**Comment by charlesoblack** [comment]
@swanson @Koronen is this project abandoned?

**Comment by swanson** [comment]
@charlesoblack Hello, this project is not under active development. But for many people (myself included) it's still running fine and fits their needs.

Sorry that you are having problems with your installation. I don't have any thoughts on what the problem would be and can't provide technical support for your own installation (outside of pointing you to the `docs` folder for 'recommended' instructions).

If you do find out the issue, please leave a note here in case someone else stumbles upon it.

**Comment by charlesoblack** [comment]
@swanson Thanks! I just figured I'd ask since the last few issues had no responses from you/Koronen.

Where are the logs for a `systemd` version of stringer stored?

**Comment by charlesoblack** [comment]
Looks like it's set to `syslog` in the `.service` files created by foreman. Here's the reason why it's such high CPU usage:

```
Jan 12 22:00:29 vps systemd[1]: stringer-console@5100.service: Service hold-off time over, scheduling restart.
Jan 12 22:00:29 vps systemd[1]: stringer-console@5100.service: Scheduled restart job, restart counter is at 48752.
Jan 12 22:00:29 vps systemd[1]: Stopped stringer-console@5100.service.
Jan 12 22:00:29 vps systemd[1]: Started stringer-console@5100.service.
Jan 12 22:00:32 vps systemd[1]: stringer-console@5100.service: Service hold-off time over, scheduling restart.
Jan 12 22:00:32 vps systemd[1]: stringer-console@5100.service: Scheduled restart job, restart counter is at 48753.
Jan 12 22:00:32 vps systemd[1]: Stopped stringer-console@5100.service.
Jan 12 22:00:32 vps systemd[1]: Started stringer-console@5100.service.
```

Now to figure out why it's failing to start...

**Comment by charlesoblack** [comment]
I disabled the `stringer-console@5100` service and nothing seems broken. I'll (tentatively...) close this for now.
